- hosts: test-server
  become: true
  tasks:
  - name: update the app
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: starte the docker service
    command: sudo systemctl start docker

  - name: deploy insurance application
    command: sudo docker run -itd -p 8084:8081 pujariprasanth/insurance:1.0
